apiVersion: skaffold/v2beta28
build:
  artifacts:
  - context: /home/afonso/sckan-explorer/cloud-harness
    docker:
      buildArgs: {DEBUG: 'true', NOCACHE: '1732128976.5210433', REGISTRY: '', TAG: null}
      dockerfile: cloud-harness/infrastructure/base-images/cloudharness-base-debian/Dockerfile
      ssh: default
    image: cloudharness/cloudharness-base-debian
  - context: /home/afonso/sckan-explorer/cloud-harness
    docker:
      buildArgs: {DEBUG: 'true', NOCACHE: '1732128976.5211222', REGISTRY: '', TAG: null}
      dockerfile: cloud-harness/infrastructure/base-images/cloudharness-base/Dockerfile
      ssh: default
    image: cloudharness/cloudharness-base
  - context: /home/afonso/sckan-explorer/cloud-harness
    docker:
      buildArgs: {DEBUG: 'true', NOCACHE: '1732128976.5211885', REGISTRY: '', TAG: null}
      dockerfile: cloud-harness/infrastructure/base-images/cloudharness-frontend-build/Dockerfile
      ssh: default
    image: cloudharness/cloudharness-frontend-build
  - context: /home/afonso/sckan-explorer/cloud-harness/infrastructure/common-images/cloudharness-flask
    docker:
      buildArgs: {DEBUG: 'true', NOCACHE: '1732128976.5223234', REGISTRY: '', TAG: null}
      dockerfile: cloud-harness/infrastructure/common-images/cloudharness-flask/Dockerfile
      ssh: default
    image: cloudharness/cloudharness-flask
    requires:
    - {alias: CLOUDHARNESS_BASE, image: cloudharness/cloudharness-base}
  - context: /home/afonso/sckan-explorer/cloud-harness/infrastructure/common-images/cloudharness-django
    docker:
      buildArgs: {DEBUG: 'true', NOCACHE: '1732128976.5224555', REGISTRY: '', TAG: null}
      dockerfile: cloud-harness/infrastructure/common-images/cloudharness-django/Dockerfile
      ssh: default
    image: cloudharness/cloudharness-django
    requires:
    - {alias: CLOUDHARNESS_BASE_DEBIAN, image: cloudharness/cloudharness-base-debian}
  - context: /home/afonso/sckan-explorer/cloud-harness/applications/common/server
    docker:
      buildArgs: {DEBUG: 'true', NOCACHE: '1732128976.5251973', REGISTRY: '', TAG: null}
      dockerfile: cloud-harness/applications/common/server/Dockerfile
      ssh: default
    image: cloudharness/common
    requires:
    - {alias: CLOUDHARNESS_FLASK, image: cloudharness/cloudharness-flask}
  - context: /home/afonso/sckan-explorer/./applications/sckanner
    docker:
      buildArgs: {DEBUG: 'true', NOCACHE: '1732128969.694781', REGISTRY: '', TAG: null}
      dockerfile: applications/sckanner/Dockerfile
      ssh: default
    image: cloudharness/sckanner
    requires:
    - {alias: CLOUDHARNESS_FRONTEND_BUILD, image: cloudharness/cloudharness-frontend-build}
    - {alias: CLOUDHARNESS_DJANGO, image: cloudharness/cloudharness-django}
  local: {concurrency: 4, useBuildkit: true}
  tagPolicy:
    sha256: {}
deploy:
  helm:
    flags:
      install: [--timeout=10m]
      upgrade: [--install]
    releases:
    - artifactOverrides:
        apps:
          common:
            harness:
              deployment: {image: cloudharness/common}
          sckanner:
            harness:
              deployment: {image: cloudharness/sckanner}
        task-images: {cloudharness-base: cloudharness/cloudharness-base, cloudharness-base-debian: cloudharness/cloudharness-base-debian,
          cloudharness-django: cloudharness/cloudharness-django, cloudharness-flask: cloudharness/cloudharness-flask,
          cloudharness-frontend-build: cloudharness/cloudharness-frontend-build}
      chartPath: deployment/helm
      name: sckanner-local
      namespace: sckanner-local
      overrides:
        apps:
          common:
            harness:
              deployment:
                args: [/usr/src/app/common/__main__.py]
                command: [python]
      skipBuildDependencies: true
kind: Config
test: []
