# Generated by Django 5.1.3 on 2024-11-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sckanner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeStatement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("data", models.JSONField()),
            ],
        ),
    ]
