# Generated by Django 5.2 on 2025-05-21 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sckanner", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectivityStatement",
            fields=[
                (
                    "id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "reference_uri",
                    models.URLField(blank=True, db_index=True, null=True),
                ),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="DataSnapshot",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "timestamp",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("version", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_start", "To Start"),
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="to_start",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reference_uri_key", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "python_code_file_for_statements_retrieval",
                    models.FileField(
                        help_text="Python file containing structure retrieval code",
                        upload_to="data_sources/retrieval/",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="KnowledgeStatement",
        ),
        migrations.AddField(
            model_name="connectivitystatement",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sckanner.datasnapshot"
            ),
        ),
        migrations.CreateModel(
            name="DataIngestion",
            fields=[],
            options={
                "verbose_name": "Data Ingestion",
                "verbose_name_plural": "Data Ingestion",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sckanner.datasnapshot",),
        ),
        migrations.AddField(
            model_name="datasnapshot",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sckanner.datasource"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="connectivitystatement",
            unique_together={("reference_uri", "snapshot")},
        ),
        migrations.AlterUniqueTogether(
            name="datasnapshot",
            unique_together={("source", "version")},
        ),
    ]
