# Generated by Django 5.2 on 2025-04-28 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sckanner", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectivityStatement",
            fields=[
                (
                    "id",
                    models.AutoField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "reference_uri",
                    models.URLField(blank=True, db_index=True, null=True),
                ),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="DataSnapshot",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "datetime",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("NEURONDM", "Neurondm"), ("COMPOSER", "Composer")],
                        db_index=True,
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="KnowledgeStatement",
        ),
        migrations.AddField(
            model_name="connectivitystatement",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sckanner.datasnapshot"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="connectivitystatement",
            unique_together={("reference_uri", "snapshot")},
        ),
    ]
