# Generated by Django 5.2 on 2025-04-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sckanner", "0003_connectivitystatement_datasnapshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnatomicalEntityHierarchy",
            fields=[
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EndOrgan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
            ],
        ),
    ]
