# Generated by Django 5.2.4 on 2025-07-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sckanner', '0004_auto_ingest_composer_and_neurondm_statements'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasnapshot',
            name='a_b_via_c_json_file',
            field=models.FileField(blank=True, null=True, upload_to='a_b_via_c_json/'),
        ),
    ]
