# Generated by Django 5.2.4 on 2025-07-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sckanner', '0006_add_a_b_via_c_to_existing_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasnapshot',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
