# Generated by Django 4.2.4 on 2025-08-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sckanner', '0007_datasnapshot_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasnapshot',
            name='snapshot_visible',
            field=models.BooleanField(default=True, db_index=True, help_text='Whether this snapshot is visible to users'),
        ),
    ]
