# Generated by Django 4.2.4 on 2025-08-05 12:00

from django.db import migrations


def set_existing_snapshots_visible(apps, schema_editor):
    """Set snapshot_visible=True for all existing DataSnapshot records"""
    DataSnapshot = apps.get_model('sckanner', 'DataSnapshot')
    DataSnapshot.objects.update(snapshot_visible=True)


def reverse_set_existing_snapshots_visible(apps, schema_editor):
    """Reverse migration - set snapshot_visible=False for all records"""
    DataSnapshot = apps.get_model('sckanner', 'DataSnapshot')
    DataSnapshot.objects.update(snapshot_visible=False)


class Migration(migrations.Migration):

    dependencies = [
        ('sckanner', '0008_add_snapshot_visible'),
    ]

    operations = [
        migrations.RunPython(
            set_existing_snapshots_visible,
            reverse_set_existing_snapshots_visible,
        ),
    ]
