# Generated by Django 5.1.3 on 2025-08-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sckanner', '0009_set_existing_snapshots_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasnapshot',
            name='default',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this is the default snapshot'),
        ),
    ]
