version: '1.0'
stages:
- prepare
- build
- unittest
- deploy
- qa
- publish
steps:
  main_clone:
    title: Clone main repository
    type: git-clone
    stage: prepare
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_BRANCH}}'
    git: github
  post_main_clone:
    title: Post main clone
    type: parallel
    stage: prepare
    steps:
      clone_cloud_harness:
        title: Cloning cloud-harness repository...
        type: git-clone
        stage: prepare
        repo: https://github.com/MetaCell/cloud-harness.git
        revision: '${{CLOUDHARNESS_BRANCH}}'
        working_directory: .
        git: github
  prepare_deployment:
    title: Prepare helm chart
    image: python:3.12
    stage: prepare
    working_directory: .
    commands:
    - bash cloud-harness/install.sh
    - harness-deployment cloud-harness . -d ${{DOMAIN}} -r ${{REGISTRY}} -rs '${{REGISTRY_SECRET}}'
      -n ${{NAMESPACE}} --write-env -e dev --cache-url '${{IMAGE_CACHE_URL}}' -i sckanner
    - cat deployment/.env >> ${{CF_VOLUME_PATH}}/env_vars_to_export
    - cat ${{CF_VOLUME_PATH}}/env_vars_to_export
  prepare_deployment_view:
    commands:
    - helm template ./deployment/helm --debug -n ${{NAMESPACE}}
    environment:
    - ACTION=auth
    - KUBE_CONTEXT=${{NAMESPACE}}
    image: codefresh/cfstep-helm:3.6.2
    stage: prepare
    title: View helm chart
  build_application_images_0:
    type: parallel
    stage: build
    steps:
      accounts:
        type: build
        stage: build
        dockerfile: Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        image_name: cloud-harness/accounts
        title: Accounts
        working_directory: ./cloud-harness/applications/accounts
        tags:
        - '${{ACCOUNTS_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{ACCOUNTS_TAG_EXISTS}}', '{{ACCOUNTS_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{ACCOUNTS_TAG_FORCE_BUILD}}', '{{ACCOUNTS_TAG_FORCE_BUILD}}')
                == false
      cloudharness-base:
        type: build
        stage: build
        dockerfile: infrastructure/base-images/cloudharness-base/Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        image_name: cloud-harness/cloudharness-base
        title: Cloudharness base
        working_directory: ./cloud-harness
        tags:
        - '${{CLOUDHARNESS_BASE_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{CLOUDHARNESS_BASE_TAG_EXISTS}}', '{{CLOUDHARNESS_BASE_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{CLOUDHARNESS_BASE_TAG_FORCE_BUILD}}', '{{CLOUDHARNESS_BASE_TAG_FORCE_BUILD}}')
                == false
      test-e2e:
        type: build
        stage: build
        dockerfile: Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        image_name: cloud-harness/test-e2e
        title: Test e2e
        working_directory: ./cloud-harness/test/test-e2e
        tags:
        - '${{TEST_E2E_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        - latest
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{TEST_E2E_TAG_EXISTS}}', '{{TEST_E2E_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{TEST_E2E_TAG_FORCE_BUILD}}', '{{TEST_E2E_TAG_FORCE_BUILD}}')
                == false
      cloudharness-frontend-build:
        type: build
        stage: build
        dockerfile: infrastructure/base-images/cloudharness-frontend-build/Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        image_name: cloud-harness/cloudharness-frontend-build
        title: Cloudharness frontend build
        working_directory: ./cloud-harness
        tags:
        - '${{CLOUDHARNESS_FRONTEND_BUILD_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{CLOUDHARNESS_FRONTEND_BUILD_TAG_EXISTS}}',
                '{{CLOUDHARNESS_FRONTEND_BUILD_TAG_EXISTS}}') == true
              forceNoCache: includes('${{CLOUDHARNESS_FRONTEND_BUILD_TAG_FORCE_BUILD}}',
                '{{CLOUDHARNESS_FRONTEND_BUILD_TAG_FORCE_BUILD}}') == false
    title: Build parallel step 1
  build_application_images_1:
    type: parallel
    stage: build
    steps:
      cloudharness-django:
        type: build
        stage: build
        dockerfile: Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        - CLOUDHARNESS_BASE=${{REGISTRY}}/cloud-harness/cloudharness-base:${{CLOUDHARNESS_BASE_TAG}}
        image_name: cloud-harness/cloudharness-django
        title: Cloudharness django
        working_directory: ./cloud-harness/infrastructure/common-images/cloudharness-django
        tags:
        - '${{CLOUDHARNESS_DJANGO_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{CLOUDHARNESS_DJANGO_TAG_EXISTS}}', '{{CLOUDHARNESS_DJANGO_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{CLOUDHARNESS_DJANGO_TAG_FORCE_BUILD}}', '{{CLOUDHARNESS_DJANGO_TAG_FORCE_BUILD}}')
                == false
      workflows-send-result-event:
        type: build
        stage: build
        dockerfile: Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        - CLOUDHARNESS_BASE=${{REGISTRY}}/cloud-harness/cloudharness-base:${{CLOUDHARNESS_BASE_TAG}}
        image_name: cloud-harness/workflows-send-result-event
        title: Workflows send result event
        working_directory: ./cloud-harness/applications/workflows/tasks/send-result-event
        tags:
        - '${{WORKFLOWS_SEND_RESULT_EVENT_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{WORKFLOWS_SEND_RESULT_EVENT_TAG_EXISTS}}',
                '{{WORKFLOWS_SEND_RESULT_EVENT_TAG_EXISTS}}') == true
              forceNoCache: includes('${{WORKFLOWS_SEND_RESULT_EVENT_TAG_FORCE_BUILD}}',
                '{{WORKFLOWS_SEND_RESULT_EVENT_TAG_FORCE_BUILD}}') == false
      workflows-extract-download:
        type: build
        stage: build
        dockerfile: Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        - CLOUDHARNESS_BASE=${{REGISTRY}}/cloud-harness/cloudharness-base:${{CLOUDHARNESS_BASE_TAG}}
        image_name: cloud-harness/workflows-extract-download
        title: Workflows extract download
        working_directory: ./cloud-harness/applications/workflows/tasks/extract-download
        tags:
        - '${{WORKFLOWS_EXTRACT_DOWNLOAD_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{WORKFLOWS_EXTRACT_DOWNLOAD_TAG_EXISTS}}',
                '{{WORKFLOWS_EXTRACT_DOWNLOAD_TAG_EXISTS}}') == true
              forceNoCache: includes('${{WORKFLOWS_EXTRACT_DOWNLOAD_TAG_FORCE_BUILD}}',
                '{{WORKFLOWS_EXTRACT_DOWNLOAD_TAG_FORCE_BUILD}}') == false
      test-api:
        type: build
        stage: build
        dockerfile: test/test-api/Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        - CLOUDHARNESS_BASE=${{REGISTRY}}/cloud-harness/cloudharness-base:${{CLOUDHARNESS_BASE_TAG}}
        image_name: cloud-harness/test-api
        title: Test api
        working_directory: ./cloud-harness
        tags:
        - '${{TEST_API_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        - latest
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{TEST_API_TAG_EXISTS}}', '{{TEST_API_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{TEST_API_TAG_FORCE_BUILD}}', '{{TEST_API_TAG_FORCE_BUILD}}')
                == false
      workflows-notify-queue:
        type: build
        stage: build
        dockerfile: Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        - CLOUDHARNESS_BASE=${{REGISTRY}}/cloud-harness/cloudharness-base:${{CLOUDHARNESS_BASE_TAG}}
        image_name: cloud-harness/workflows-notify-queue
        title: Workflows notify queue
        working_directory: ./cloud-harness/applications/workflows/tasks/notify-queue
        tags:
        - '${{WORKFLOWS_NOTIFY_QUEUE_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{WORKFLOWS_NOTIFY_QUEUE_TAG_EXISTS}}',
                '{{WORKFLOWS_NOTIFY_QUEUE_TAG_EXISTS}}') == true
              forceNoCache: includes('${{WORKFLOWS_NOTIFY_QUEUE_TAG_FORCE_BUILD}}',
                '{{WORKFLOWS_NOTIFY_QUEUE_TAG_FORCE_BUILD}}') == false
      cloudharness-flask:
        type: build
        stage: build
        dockerfile: Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        - CLOUDHARNESS_BASE=${{REGISTRY}}/cloud-harness/cloudharness-base:${{CLOUDHARNESS_BASE_TAG}}
        image_name: cloud-harness/cloudharness-flask
        title: Cloudharness flask
        working_directory: ./cloud-harness/infrastructure/common-images/cloudharness-flask
        tags:
        - '${{CLOUDHARNESS_FLASK_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{CLOUDHARNESS_FLASK_TAG_EXISTS}}', '{{CLOUDHARNESS_FLASK_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{CLOUDHARNESS_FLASK_TAG_FORCE_BUILD}}', '{{CLOUDHARNESS_FLASK_TAG_FORCE_BUILD}}')
                == false
    title: Build parallel step 2
  build_application_images_2:
    type: parallel
    stage: build
    steps:
      sckanner:
        type: build
        stage: build
        dockerfile: Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        - CLOUDHARNESS_FRONTEND_BUILD=${{REGISTRY}}/cloud-harness/cloudharness-frontend-build:${{CLOUDHARNESS_FRONTEND_BUILD_TAG}}
        - CLOUDHARNESS_DJANGO=${{REGISTRY}}/cloud-harness/cloudharness-django:${{CLOUDHARNESS_DJANGO_TAG}}
        image_name: cloud-harness/sckanner
        title: Sckanner
        working_directory: ./applications/sckanner
        tags:
        - '${{SCKANNER_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{SCKANNER_TAG_EXISTS}}', '{{SCKANNER_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{SCKANNER_TAG_FORCE_BUILD}}', '{{SCKANNER_TAG_FORCE_BUILD}}')
                == false
      workflows:
        type: build
        stage: build
        dockerfile: Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        - CLOUDHARNESS_FLASK=${{REGISTRY}}/cloud-harness/cloudharness-flask:${{CLOUDHARNESS_FLASK_TAG}}
        image_name: cloud-harness/workflows
        title: Workflows
        working_directory: ./cloud-harness/applications/workflows/server
        tags:
        - '${{WORKFLOWS_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{WORKFLOWS_TAG_EXISTS}}', '{{WORKFLOWS_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{WORKFLOWS_TAG_FORCE_BUILD}}', '{{WORKFLOWS_TAG_FORCE_BUILD}}')
                == false
    title: Build parallel step 3
  deployment:
    stage: deploy
    type: helm
    working_directory: ./${{CF_REPO_NAME}}
    title: Installing chart
    arguments:
      helm_version: 3.6.2
      chart_name: deployment/helm
      release_name: '${{NAMESPACE}}'
      kube_context: '${{CLUSTER_NAME}}'
      namespace: '${{NAMESPACE}}'
      chart_version: '${{CF_BUILD_ID}}'
      cmd_ps: --wait --timeout 600s --create-namespace
      custom_value_files:
      - ./deployment/helm/values.yaml
      custom_values: []
  tests_api:
    stage: qa
    title: Api tests
    working_directory: /home/test
    image: '${{REGISTRY}}/cloud-harness/test-api:${{TEST_API_TAG}}'
    fail_fast: false
    commands:
    - echo $APP_NAME
    scale:
      workflows_api_test:
        title: workflows api test
        volumes:
        - '${{CF_REPO_NAME}}/cloud-harness/applications/workflows:/home/test'
        - '${{CF_REPO_NAME}}/deployment/helm/values.yaml:/opt/cloudharness/resources/allvalues.yaml'
        environment:
        - APP_URL=https://workflows.${{DOMAIN}}/api
        commands:
        - st --pre-run cloudharness_test.apitest_init run api/openapi.yaml --base-url
          https://workflows.${{DOMAIN}}/api -c all
    when:
      condition:
        all:
          whenVarExists: includes("${{SKIP_TESTS}}", "{{SKIP_TESTS}}") == true
  approval:
    type: pending-approval
    stage: publish
    title: Approve build
    description: Approve build release and tagging
    timeout:
      duration: 168
      finalState: denied
  publish:
    type: parallel
    stage: publish
    steps:
      publish_cloudharness-base:
        stage: publish
        type: push
        title: Cloudharness base
        candidate: '${{REGISTRY}}/cloud-harness/cloudharness-base:${{CLOUDHARNESS_BASE_TAG}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        - latest
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_cloudharness-frontend-build:
        stage: publish
        type: push
        title: Cloudharness frontend build
        candidate: '${{REGISTRY}}/cloud-harness/cloudharness-frontend-build:${{CLOUDHARNESS_FRONTEND_BUILD_TAG}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        - latest
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_cloudharness-flask:
        stage: publish
        type: push
        title: Cloudharness flask
        candidate: '${{REGISTRY}}/cloud-harness/cloudharness-flask:${{CLOUDHARNESS_FLASK_TAG}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        - latest
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_cloudharness-django:
        stage: publish
        type: push
        title: Cloudharness django
        candidate: '${{REGISTRY}}/cloud-harness/cloudharness-django:${{CLOUDHARNESS_DJANGO_TAG}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        - latest
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_workflows-send-result-event:
        stage: publish
        type: push
        title: Workflows send result event
        candidate: '${{REGISTRY}}/cloud-harness/workflows-send-result-event:${{WORKFLOWS_SEND_RESULT_EVENT_TAG}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        - latest
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_workflows-notify-queue:
        stage: publish
        type: push
        title: Workflows notify queue
        candidate: '${{REGISTRY}}/cloud-harness/workflows-notify-queue:${{WORKFLOWS_NOTIFY_QUEUE_TAG}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        - latest
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_workflows-extract-download:
        stage: publish
        type: push
        title: Workflows extract download
        candidate: '${{REGISTRY}}/cloud-harness/workflows-extract-download:${{WORKFLOWS_EXTRACT_DOWNLOAD_TAG}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        - latest
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_workflows:
        stage: publish
        type: push
        title: Workflows
        candidate: '${{REGISTRY}}/cloud-harness/workflows:${{WORKFLOWS_TAG}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        - latest
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_accounts:
        stage: publish
        type: push
        title: Accounts
        candidate: '${{REGISTRY}}/cloud-harness/accounts:${{ACCOUNTS_TAG}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        - latest
        registry: '${{REGISTRY_PUBLISH_URL}}'
      publish_sckanner:
        stage: publish
        type: push
        title: Sckanner
        candidate: '${{REGISTRY}}/cloud-harness/sckanner:${{SCKANNER_TAG}}'
        tags:
        - '${{DEPLOYMENT_PUBLISH_TAG}}'
        - latest
        registry: '${{REGISTRY_PUBLISH_URL}}'
    when:
      condition:
        all:
          whenVarExists: includes("${{DEPLOYMENT_PUBLISH_TAG}}", "{{DEPLOYMENT_PUBLISH_TAG}}")
            == false
